title: 'Mahdi Hussein | مهدي حسين'

params: 
  navbar_title: "Mahdi Hussein"
  favicon: "/static/favicon.ico"
  socials:
    - link: "https://linkedin.com/in/mahdihussein"
      image: "/linkedin (2).svg"

module:
  hugoVersion:
    extended: false
    min: "0.116.0"